fix: conflicting declaration error message utility
this commit produces:
```console
error: The option `networking.networkmanager.enable' has conflicting definition values:
       - In `/nix/store/7mnkd3pky8vhdb113jwm1yx86jpx5f9l-source/tests/fullFlake/profiles/core': true
       - In `/nix/store/7mnkd3pky8vhdb113jwm1yx86jpx5f9l-source/tests/fullFlake/hosts/NixOS.nix': false
```

instead of:
```console
error: The option `networking.networkmanager.enable' has conflicting definition values:
       - In `/nix/store/b6wbmpjx59bls58bgng7bip1q3pvl3pd-source/tests/fullFlake/profiles/core': true
       - In `<unknown-file>': false
```